# Example Prometheus scrape config to add to your Prometheus server
scrape_configs:
  - job_name: 'fedex'
    metrics_path: /metrics
    static_configs:
      - targets: ['your-hostname:3000']

# Example Alertmanager receiver config is required to forward alerts to e.g. Slack or PagerDuty
# See monitoring/alerts.yaml for rule examples.
